let zetechplug = async (m, { conn, reply, trashown }) => {
    try {
        // Check if user is owner
        if (!trashown) return reply("*❌ Only owner can use this command*");

        await reply("_Fetching your groups and channels..._");

        let groupsList = "📋 *YOUR GROUPS & CHANNELS*\n\n";
        let groupCount = 0;
        let channelCount = 0;

        // Get all chats (groups and channels)
        const chats = await conn.getChats();
        
        for (let chat of chats) {
            if (chat.id.endsWith('@g.us')) {
                // This is a group
                groupCount++;
                const groupName = chat.name || "Unknown Group";
                const groupJid = chat.id;
                
                groupsList += `👥 *Group ${groupCount}:*\n`;
                groupsList += `📛 Name: ${groupName}\n`;
                groupsList += `🆔 JID: \`${groupJid}\`\n\n`;
                
            } else if (chat.id.endsWith('@newsletter')) {
                // This is a channel
                channelCount++;
                const channelName = chat.name || "Unknown Channel";
                const channelJid = chat.id;
                
                groupsList += `📢 *Channel ${channelCount}:*\n`;
                groupsList += `📛 Name: ${channelName}\n`;
                groupsList += `🆔 JID: \`${channelJid}\`\n\n`;
            }
        }

        // Add summary
        groupsList += `📊 *SUMMARY:*\n`;
        groupsList += `👥 Groups: ${groupCount}\n`;
        groupsList += `📢 Channels: ${channelCount}\n`;
        groupsList += `📱 Total: ${groupCount + channelCount}\n\n`;
        groupsList += `*Generated by Zetech-MD*`;

        if (groupCount === 0 && channelCount === 0) {
            groupsList = "📋 *YOUR GROUPS & CHANNELS*\n\n❌ *No groups or channels found*\n\n*You are not a member of any groups or channels.*";
        }

        await reply(groupsList);

    } catch (error) {
        console.error('[GROUPS ERROR] Error in groups command:', error);
        reply("❌ *Failed to fetch groups and channels. Please try again later.*");
    }
};

zetechplug.help = ['groups']
zetechplug.tags = ['owner']
zetechplug.command = ['groups', 'mychats', 'listgroups']

module.exports = zetechplug;
