let zetechplug = async (m, { conn, reply, trashown }) => {
    try {
        // Check if sender is in owner list manually
        const senderNumber = m.sender.replace('@s.whatsapp.net', '');
        const isOwnerManual = global.owner.includes(senderNumber) || global.owner.includes(senderNumber.replace('+', ''));
        
        // Send debug information to owner's DM
        const debugInfo = `🔍 *GROUPS PLUGIN DEBUG*\n\n` +
            `📱 *Sender:* ${m.sender}\n` +
            `👑 *Global Owner:* ${JSON.stringify(global.owner)}\n` +
            `✅ *Trashown:* ${trashown}\n` +
            `🔢 *Sender Number:* ${senderNumber}\n` +
            `✅ *Manual Owner Check:* ${isOwnerManual}\n` +
            `⏰ *Time:* ${new Date().toLocaleString()}`;
        
        // Send debug info to owner's DM
        try {
            const ownerNumber = global.owner[0] + '@s.whatsapp.net';
            await conn.sendMessage(ownerNumber, { text: debugInfo });
        } catch (e) {
            console.log('Failed to send debug info to owner');
        }
        
        // Check if user is owner
        if (!trashown && !isOwnerManual) {
            return reply(`*❌ Only owner can use this command*\n\n*Debug info sent to owner's DM*`);
        }

        await reply("_Fetching your groups and channels..._");

        let groupsList = "📋 *YOUR GROUPS & CHANNELS*\n\n";
        let groupCount = 0;
        let channelCount = 0;

        // Try different methods to get chats
        let chats = [];
        
        try {
            // Method 1: Try getChats()
            if (conn.getChats) {
                chats = await conn.getChats();
            }
        } catch (e) {
            console.log('[GROUPS] getChats() failed, trying alternative method');
        }

        // If getChats() failed or returned empty, try alternative method
        if (!chats || chats.length === 0) {
            try {
                // Method 2: Try to get chats from store
                if (conn.store && conn.store.chats) {
                    chats = Object.values(conn.store.chats.all());
                }
            } catch (e) {
                console.log('[GROUPS] Store method failed, trying direct access');
            }
        }

        // If still no chats, try direct access to conn.chats
        if (!chats || chats.length === 0) {
            try {
                if (conn.chats) {
                    chats = Object.values(conn.chats);
                }
            } catch (e) {
                console.log('[GROUPS] Direct chats access failed');
            }
        }

        console.log(`[GROUPS] Found ${chats ? chats.length : 0} chats`);

        if (chats && chats.length > 0) {
            for (let chat of chats) {
                try {
                    if (chat.id && chat.id.endsWith('@g.us')) {
                        // This is a group
                        groupCount++;
                        const groupName = chat.name || chat.subject || "Unknown Group";
                        const groupJid = chat.id;
                        
                        groupsList += `👥 *Group ${groupCount}:*\n`;
                        groupsList += `📛 Name: ${groupName}\n`;
                        groupsList += `🆔 JID: \`${groupJid}\`\n\n`;
                        
                    } else if (chat.id && chat.id.endsWith('@newsletter')) {
                        // This is a channel
                        channelCount++;
                        const channelName = chat.name || chat.subject || "Unknown Channel";
                        const channelJid = chat.id;
                        
                        groupsList += `📢 *Channel ${channelCount}:*\n`;
                        groupsList += `📛 Name: ${channelName}\n`;
                        groupsList += `🆔 JID: \`${channelJid}\`\n\n`;
                    }
                } catch (chatError) {
                    console.warn('[GROUPS] Error processing chat:', chatError.message);
                }
            }
        }

        // Add summary
        groupsList += `📊 *SUMMARY:*\n`;
        groupsList += `👥 Groups: ${groupCount}\n`;
        groupsList += `📢 Channels: ${channelCount}\n`;
        groupsList += `📱 Total: ${groupCount + channelCount}\n\n`;
        groupsList += `*Generated by Zetech-MD*`;

        if (groupCount === 0 && channelCount === 0) {
            groupsList = "📋 *YOUR GROUPS & CHANNELS*\n\n❌ *No groups or channels found*\n\n*Possible reasons:*\n• You are not a member of any groups/channels\n• Bot needs to be restarted to refresh chat list\n• Try using the command in a group where the bot is present";
        }

        await reply(groupsList);

    } catch (error) {
        console.error('[GROUPS ERROR] Error in groups command:', error);
        reply("❌ *Failed to fetch groups and channels.*\n\n*Possible solutions:*\n• Restart the bot\n• Try the command in a group\n• Check bot permissions");
    }
};

zetechplug.help = ['groups']
zetechplug.tags = ['owner']
zetechplug.command = ['groups', 'mychats', 'listgroups']

module.exports = zetechplug;
